site_name: Struct Beaver
site_url: https://structbeaver.com

theme:
  name: material
  custom_dir: overrides
  features:
   - search
   - search.suggest
   - search.highlight
   - navigation.instant
   - navigation.instant.prefetch
   - navigation.instant.progress
   - navigation.expand
   - navigation.path
   - navigation.prune
   - navigation.indexes
   - toc.follow
   - content.code.copy
   - content.code.select
   
  palette:
    
     # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

nav:
  - 1. Vetores:
    - vetores/index.md
    - 1.1 Uso básico: vetores/uso-basico.md
    - 1.2 Pesquisa simples: vetores/pesquisa_simples.md
    - 1.3 Pesquisa binaria: vetores/pesquisa_binaria.md
  - 2. Recursividade:
    - recursividade/index.md
    - 2.1 Funções recursivas: recursividade/funcoes-recursivas.md
    - 2.2 Sequência de Fibonacci: recursividade/fibonacci.md
  - 3. Notação Big O: 
    - notacaoBigO/index.md
    - 3.1 Como calcular o tempo de execução: notacaoBigO/calculo-tempo-execucao.md
  - 4. Ordenação:
    - ordenacao/index.md
    - 4.1 Ordenação usando o método da bolha (Bubble Sort): ordenacao/bubble-sort.md
    - 4.2 Ordenação usando o método de seleção (Selection Sort): ordenacao/selection-sort.md
    - 4.3 Ordenação usando o método de inserção (Insertion Sort): ordenacao/insertion-sort.md
    - 4.4 Ordenação usando o método de ordenação rápida (Quick Sort): ordenacao/quick-sort.md
    - 4.5 Ordenação usando o Merge Sort: ordenacao/merge-sort.md
  - 5. Pilhas:
    - pilhas/index.md
    - 5.1 Pilhas e suas operações: pilhas/pilhas-operacoes.md
    - 5.2 Implementação padrão de pilhas usando C#: pilhas/pilhas-c-sharp.md


markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
 - search
 - glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       slide_effect: slide
       width: 100%
       height: auto
       zoomable: true
       draggable: true       
       auto_caption: false
       background: white
       shadow: true
       manual: false

extra_css:
  - assets/styles.css
